# Generated by Django 3.1.1 on 2021-02-01 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20210201_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='restaurants.restaurant'),
        ),
    ]
